# Generated by Django 5.0.6 on 2024-05-11 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('picture', models.ImageField(upload_to='hostel_pictures/')),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('number_of_rooms', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('hostelmanager', 'Hostel Manager')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel')),
                ('room_number', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.room')),
                ('client_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostel.userp')),
            ],
        ),
    ]
